### PR TITLE
Disallow console statements

### PR DESCRIPTION
**Pull request by mpelzsherman**
ednamode_noconsole

### CODE REVIEW

**Comment by tadjohnston** [comment]
We're using the [default from airbnb](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/errors.js#L22-L23).  I'm trying to understand why airbnb would make it a warn and not an error.  Did you try this locally?

**Comment by mpelzsherman** [comment]
I did try it locally. I don't understand why airbnb makes it a warn, but I don't think WE should!

**Comment by colinrymer** [comment]
I'm all for this, but thought we were already doing it. Did they recently change it to a warn?

**Comment by bethstevic** [comment]
Looks good to me, there are a few places, I think in the large code, where we do want a console log so you will need to add `// eslint-disable-line no-console`

**Comment by mpelzsherman** [comment]
As far as I can tell it's always been a warn.

**Comment by mpelzsherman** [comment]
We are already using `// eslint-disable-line no-console` as needed.

**Comment by LinnJS** [comment]
I accidentally pushed a CL the other day and was wondering why it let me push it. Good rule to have in place!

**Pull request merged**
